### PR TITLE
Refactor SelectInstrument component with carousel

### PR DESCRIPTION
**Pull request by NerdDiffer**
TODO:
- fix display of "Previous" button
- Get the "logo" to show up
- remove outlines

### CODE REVIEW

**Comment by ghost** [comment]
Hey, I'm getting unexpected token on line 162 in Room when webpacking. Can't figure out the issue.

**Comment by NerdDiffer** [comment]
Yea, me too. Forgot about that. Will fix

Rafael Espinoza
_www.rafaelespinoza.com_ http://www.rafaelespinoza.com

**Comment by ghost** [comment]
In general, it looks ok. Can you add a prev button? What's the issue with the start button?

**Comment by NerdDiffer** [comment]
Using #64 instead

**Pull request closed without merging**
